/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppEquipmentRouteImport } from './routes/app.equipment'
import { Route as AppEstimatingRouteImport } from './routes/app.estimating'
import { Route as AppFinancialsRouteImport } from './routes/app.financials'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppTeamRouteImport } from './routes/app.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatingRoute = AppEstimatingRouteImport.update({
  id: '/estimating',
  path: '/estimating',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/estimating': typeof AppEstimatingRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/estimating': typeof AppEstimatingRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/estimating': typeof AppEstimatingRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/crm'
    | '/app/equipment'
    | '/app/estimating'
    | '/app/financials'
    | '/app/projects'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/crm'
    | '/app/equipment'
    | '/app/estimating'
    | '/app/financials'
    | '/app/projects'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/crm'
    | '/app/equipment'
    | '/app/estimating'
    | '/app/financials'
    | '/app/projects'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipment': {
      id: '/app/equipment'
      path: '/equipment'
      fullPath: '/app/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estimating': {
      id: '/app/estimating'
      path: '/estimating'
      fullPath: '/app/estimating'
      preLoaderRoute: typeof AppEstimatingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppEstimatingRoute: typeof AppEstimatingRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCrmRoute: AppCrmRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppEstimatingRoute: AppEstimatingRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
